include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - "**/**.g.dart"
    - "**/**.config.dart"
    - "**/**.config.dart"
    - "**/firebase_options_prod.dart"
    - "**/firebase_options_dev.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/**.freezed.dart"
    - "**.yaml"
  errors:
    invalid_annotation_target: ignore
    mixin_inherits_from_not_object: ignore
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    directives_ordering: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
