name: mi_mercadito_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.3.8

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  fpdart: ^1.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  #url_launcher: ^6.3.0
  injectable: ^2.4.1
  get_it: ^7.6.7
  dio: ^5.4.1

  #=============================>
  # State
  #=============================>
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  built_collection: ^5.1.1
  bloc_concurrency: ^0.2.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  #=============================>
  # Widgets
  #=============================>
  # cached_network_image: ^3.3.1
  #  url_launcher: ^6.2.5

  google_fonts: ^6.2.1
  themexpert: ^1.0.2
  rate_in_stars: ^0.0.3

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^3.1.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true
